# Generated by Django 5.1.4 on 2024-12-11 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sponsor_To_Student',
            new_name='StudentSponsor',
        ),
        migrations.RenameModel(
            old_name='OTM',
            new_name='University',
        ),
        migrations.RenameField(
            model_name='sponsor',
            old_name='sponsership',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='sponsor',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='contract',
            new_name='contract_amount',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='otm_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='otm',
        ),
        migrations.RemoveField(
            model_name='student',
            name='study_type',
        ),
        migrations.AddField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('bakalavr', 'Bakalavr'), ('magister', 'Magister')], default='Bakalavr', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='common.university'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('in_moderation', 'Moderatsiyada'), ('confirmed', 'Tasdiqlangan'), ('canceled', 'Bekor qilingan')], default='Moderatsiyada', max_length=255),
        ),
    ]
