# Generated by Django 5.1.4 on 2024-12-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rename_sponsor_to_student_studentsponsor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='sponsor_type',
            field=models.CharField(choices=[('physical_person', 'Jismoniy shaxs'), ('legal_entity', 'Yuridik shaxs')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
