# Generated by Django 5.1.4 on 2024-12-11 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_sponsor_organization_name_sponsor_sponsor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.university'),
        ),
    ]
