# Generated by Django 5.1.4 on 2024-12-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_sponsor_sponsor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_type',
            field=models.CharField(choices=[('physical_person', 'Jismoniy shaxs'), ('legal_entity', 'Yuridik shaxs')], default='physical_person', max_length=255),
        ),
    ]
